### ISSUE TITLE
check if compile on android 9/android 10

### ISSUE THREAD

**Issue by alsd4git** [alsd4git/chanu#1]
this project is a little old now, and still a mess, if anyone has time to fix thing here and there any help is appreciated, also if i remember well it uses old android libraries, and theme looks outdated

**Comment by devnyar** [comment]
Hi, I'm new come here and I want to test this on Pixel 2 XL which run Android 10.

**Comment by alsd4git** [comment]
okay, thanks

**Comment by devnyar** [comment]
I've just updated the compileSdkVersion to 29 for Android 10. And seem most things work normally. If I have more times I will try to replace android old libraries with new one.

**Comment by arifpurnama** [comment]
run in nokia 5.1 android 9

**Comment by arifpurnama** [comment]
but update SDK to 29

**Comment by alsd4git** [comment]
I started working again on this, and noted that the gallery library included don't work if targetSdkVersion is 26 or greater when opening Gallery view we have a SecurityException because there is no valid content provider
